version: '2'
services:
    jhipstermongo-app:
        image: jhipstermongo
        external_links:
            - jhipstermongo-mongodb:mongodb
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=jhipstermongo
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipstermongo-mongodb:
        extends:
            file: mongodb.yml
            service: jhipstermongo-mongodb
