version: '2'
services:
    jhipstermongo-mongodb:
        container_name: jhipstermongo-mongodb
        image: mongo:3.2.10
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/jhipstermongo/mongodb/:/data/db/
